#端口配置
server:
    port: 8080
    session-timeout: 600
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://localhost;DatabaseName=gktj
      username: sa
      password: HNGXhngx1234
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,log4j
      logSlowSql: false
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
    jpa:
        database: SQL_SERVER
        show-sql: true
        ddl-auto: create
        hibernate:
          naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.SQLServer2008Dialect
    data:
        mongodb:
          database: gktj
          uri: mongodb://localhost:27017
    mvc:
      servlet:
            load-on-startup: 1
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zr.model
#pagehelper分页插件
pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
token:
  expire:
    seconds: 1000
controller:
  scanPackage: com.zr
logging:
  config: classpath:logback-spring.xml